### ISSUE TITLE
FREEPDB1(3):kpolnb: Logon failed because the client is missing the KZTVOV_KPCLOG_O9L_LP capability flag.

### ISSUE THREAD

**Issue by PeterMerkert** [gvenzl/oci-oracle-free#6]
Hi @gvenzl , as you know, we love your images at retraced, so I gave it a try. Now, I want to start utilizing the APP_USER rather than writing an initialization script as we did so far in 21c and 19c. However, there is an odd behaviour when using the APP_USER when connecting from SQL developer to the 23c free; attempting the connect it denies it and says in the docker output: `FREEPDB1(3):kpolnb: Logon failed because the client is missing the KZTVOV_KPCLOG_O9L_LP capability flag.`.

![image](https://github.com/gvenzl/oci-oracle-free/assets/37897665/8f9b4b37-8c10-4f8a-a09e-715d364e01d0)

If I connect with the SYSTEM with the set password, all works fine:
![image](https://github.com/gvenzl/oci-oracle-free/assets/37897665/86a0ad73-30ba-4981-bedf-87c9206cba43)

I tried searching for the error in the web, but can only find unsuitable results. Maybe any setting I am missing?

SQL developer is latest version
![image](https://github.com/gvenzl/oci-oracle-free/assets/37897665/204970e7-398c-446e-ae38-b496d42d2029)

**Comment by gvenzl** [comment]
Hey @PeterMerkert,

Thanks a lot for using these images!

You are running into a compatibility issue here. Starting with Oracle Database 23c, user passwords can be up to 1024 bytes (prior to 23c it was only 30 bytes), but older clients aren't able to pass the longer password over the authentication protocol. Hence you are seeing that message in the alert log, the database essentially is saying that the authentication fails because the client cannot send such a long password.

If you shorten the password to 30 bytes or less, it will work as expected.

**Comment by PeterMerkert** [comment]
Hi Gerlad, true it works. Sorry, was not aware of that. Maybe we can shorten the password in the documentation to `password_i_should_change`, because that would just lower the possibility for people giving it a try and running into that compatibility issue like me 💘

https://github.com/gvenzl/oci-oracle-free/pull/7

No worries if you decline. No hard feelings 😀
You can decide to close this issue.

**Comment by gvenzl** [comment]
Glad to hear that! Yeah, neither was I until you brought it up. :) Will circle back with the Dev team and see whether we can provide a better, perhaps user-facing error message.

Thanks for the PR, makes sense!
